### PR TITLE
Modified Device interface (static polymorphism and Synchronous)

### PR DESCRIPTION
**Pull request by astralien3000**
There is some big modifications of the device interface.
- First, there is no more virtual methods for `Input` and `Output` classes. The polymorphism has been replaced by a static polymorphism pattern (so that everything is template).
- Then, I introduced the Asynchronous interface. The aim of asynchronous interface is to describe a device that is updated asynchronously from the main thread. (In other words, it will be updated by interruptions). It is useful for devices like [SystemController](https://github.com/AversivePlusPlus/device-control/blob/master/include/device/control/controller.hpp), which may need the filters to be evaluated at a constant period.

ps: I think pull requests will not be easy to manage with the module system...

### CODE REVIEW

**Comment by Elioty** [comment]
> ps: I think pull requests will not be easy to manage with the module system...

I agree. Even the Linux kernel uses only one monolithic git repo (but has many many forks, but you can easily have different "remote" with git so that's not much of a problem for developers).

It's a complete mess to review the commits/patches/diffs that way :X

**Comment by astralien3000** [comment]
Well, the best way to have a proper diff is to not use git submodules, and "copy" modules' code.
But modules would remain on a separate repos...

Anyway, what do you think of this changes ?

**Comment by astralien3000** [comment]
As we discussed, indeed, the reinterpret_cast can be a problem because the pointer can change between the base class and the derived class. But the static_cast instruction solve the problem !

Here is the test I used : 

``` c++
#include <iostream>
using namespace std;

template<typename Derived>
class Base {
protected:
  int c = 3;

public:
  void test1(void) {
    reinterpret_cast<Derived*>(this)->test1();
  }

  void test2(void) {
    static_cast<Derived*>(this)->test2();
  }
};

class Test {
private:
  int a = 1; 
  int b = 2;
};

class A
  : public Test,
    public Base<A> {
public:
  void test(void) {
    cout << "this " << this << endl;
    cout << "test" << c << endl;
  }

  void test1(void) {
    test();
  }
  void test2(void) {
    test();
  }
};

template<typename Derived>
void test(Base<Derived>& b) {
  cout << endl << "class Base" << endl;
  b.test1();
  b.test2();
}

int main() {
  A a;

  cout << endl << "class A" << endl;
  a.test1();
  a.test2();

  test(a);

  return 0;
}
```

The pointers displayed by test1 method should be different between a direct call to A::test1, and a call to Base<A>::test1. But for test2, it should be the same.

An other remark is that there is no pointer "offset" when the Base class has no data. So if you remove the "c" attribute, reinterpret_cast and static_cast should behave the same. That is why I did not get any problem until now.

Have you an other comment ?

**Comment by Elioty** [comment]
If you didn't forget to update any submodules to use static_cast instead of reinterpret_cast, it's ok by me, no other comment. That was the only thing that caught my mind as I reviewed the code. The design pattern looks good ;)

**Comment by astralien3000** [comment]
Grep is the answer ;)

``` bash
grep reinterpret_cast -r ./modules/
```

Thanks, let's merge !

**Pull request merged**
